=== roii/communiiity-legacy/ModelGlue/modelglue.dtd
<!ELEMENT modelglue (controllers,event-handlers,include*,config*)><!ELEMENT config (setting*)> <!ELEMENT setting (#PCDATA)> <!ATTLIST setting name CDATA #REQUIRED value CDATA #REQUIRED> <!ATTLIST include template CDATA #REQUIRED> <!ELEMENT controllers (controller+)> <!ELEMENT controller (message-listener+)> <!ATTLIST controller name CDATA #REQUIRED type CDATA #REQUIRED> <!ELEMENT message-listener (#PCDATA)> <!ATTLIST message-listener message CDATA #REQUIRED function CDATA #REQUIRED> <!ELEMENT event-handlers (event-handler|scaffold)+> <!ELEMENT scaffold (broadcasts*,results*,views*)> <!ATTLIST scaffold object CDATA #REQUIRED type CDATA #IMPLIED access CDATA #IMPLIED> <!ELEMENT event-handler (broadcasts*,results*,views*)> <!ATTLIST event-handler name CDATA #REQUIRED access CDATA #IMPLIED> <!ELEMENT broadcasts (message*)> <!ELEMENT message (argument*)> <!ATTLIST message name CDATA #REQUIRED> <!ELEMENT argument (#PCDATA)> <!ATTLIST argument name CDATA #REQUIRED value CDATA #REQUIRED> <!ELEMENT results (result*)> <!ELEMENT result (#PCDATA)> <!ATTLIST result name CDATA #IMPLIED do CDATA #REQUIRED redirect CDATA #IMPLIED append CDATA #IMPLIED anchor CDATA #IMPLIED preserveState CDATA #IMPLIED reset CDATA #IMPLIED> <!ELEMENT views (include*,value*)> <!ELEMENT include (value*)> <!ATTLIST include name CDATA #IMPLIED template CDATA #REQUIRED append CDATA #IMPLIED> <!ELEMENT value (#PCDATA)> <!ATTLIST value name CDATA #REQUIRED value CDATA #REQUIRED overwrite CDATA #IMPLIED>

=== roii/communiiity-legacy/wiki/config/ModelGlue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modelglue SYSTEM "http://www.web-relevant.com/modelglue/modelglue.dtd"
>

<modelglue>

	<controllers>
		<controller name="myController" type="wiki.controller.Controller">
			<message-listener message="OnRequestStart" function="OnRequestStart" />
			<message-listener message="OnRequestEnd" function="OnRequestEnd" />
			<message-listener message="CheckForPrintable" function="CheckForPrintable" />
			<message-listener message="CommitPage" function="CommitPage" />
			<message-listener message="DeletePage" function="DeletePage" />
			<message-listener message="EditInstructions" function="EditInstructions" />
			<message-listener message="GetPageRender" function="GetPageRender" />
			<message-listener message="LogPageView" function="LogPageView" />
			<message-listener message="MovePage" function="MovePage" />
			<message-listener message="NeedDefaultPageAuthRoles" function="getDefaultPageAuthRoles" />
			<message-listener message="NeedOrphanedPages" function="GetOrphanedPages" />
			<message-listener message="NeedPageCredentials" function="getPageCredentials" />
			<message-listener message="NeedRecentUpdates" function="GetRecentUpdates" />
			<message-listener message="NeedWhatLinksHere" function="GetWhatLinksHere" />
			<message-listener message="PageChildren" function="GetPageChildren" />
			<message-listener message="PageDiff" function="GetPageDiff" />
			<message-listener message="PageHistory" function="GetPageHistory" />
			<message-listener message="PageIndex" function="GetPageIndex" />
			<message-listener message="Search" function="Search" />
			<message-listener message="UploadFile" function="UploadFile" />
			<message-listener message="ValidatePageCredentials" function="ValidatePageCredentials" />
			<message-listener message="ValidateUploadEnabled" function="ValidateUploadEnabled" />
		</controller>
		<controller name="UserController" type="wiki.controller.UserController"> 
			<message-listener message="OnRequestStart" function="OnRequestStart" />
			<message-listener message="ValidateLogin" function="DoValidateLogin" />
			<message-listener message="Logout" function="DoLogout" />
			<message-listener message="CheckIfLoggedIn" function="DoCheckIfLoggedIn" />
			<message-listener message="SaveEventValues" function="DoSaveEventValues" />
			<message-listener message="RestoreEventValues" function="DoRestoreEventValues" />
			<message-listener message="NeedUserCredentials" function="getUserCredentials" />
			<message-listener message="NeedUserConfig" function="GetUserConfig" />
		</controller>
	</controllers>
  
	<event-handlers>
    
    <!-- USER SECURITY -->
	<event-handler name="Logout">
		<broadcasts>
			<message name="Logout" />
		</broadcasts>
		<results>
			<result do="Main" append="true" />
		</results>
	</event-handler>
	<event-handler name="LoginForm">
		<broadcasts />
		<views>
			<include name="body" template="dsp.loginform.cfm" />
		</views>
		<results>
			<result do="Layout" />
		</results>
	</event-handler>

	<event-handler name="SubmitLoginForm">
		<broadcasts>
			<message name="ValidateLogin" />
		</broadcasts>
		<views />
		<results>
			<result name="invalid" do="LoginForm" />
			<!-- a valid result will forward to the PostLoginEvent in the UserController -->
		</results>
	</event-handler>
		
    <!-- CANVAS WIKI DEFAULT -->
	<event-handler name="CommitPage">
		<broadcasts>
			<message name="CheckIfLoggedIn">
				<argument name="returnToEvent" value="CommitPage" />
				<argument name="pageMode" value="EDIT" />
			</message>
			<message name="NeedPageCredentials">
				<argument name="pageMode" value="EDIT" />
			</message>
			<message name="NeedUserCredentials" />
			<message name="ValidatePageCredentials" />
		</broadcasts>
		<results>
			<result name="invalidRole" do="InvalidRole" />
			<result name="validRole" do="CommitPageRender" />
		</results>
	</event-handler>
	
	<event-handler name="CommitPageRender" access="private">
		<broadcasts>
			<message name="CommitPage" />
		</broadcasts>
		<results>
			<result name="success" do="Main" redirect="yes" append="path"/>
			<result name="invalid" do="Edit" />
		</results>
	</event-handler>
	
	<event-handler name="Main">
		<broadcasts>
			<message name="CheckIfLoggedIn">
				<argument name="returnToEvent" value="Main" />
			</message>
			<!-- check user vs. page security to see if we can even output this page  -->
			<message name="NeedPageCredentials">
				<argument name="pageMode" value="VIEW" />
			</message>
			<message name="NeedUserCredentials" />
			<message name="ValidatePageCredentials" />
		</broadcasts>
		<views />
		<results>
			<result name="invalidRole" do="InvalidRole" />
			<result name="validRole" do="MainRender" />
		</results>
	</event-handler>

	<event-handler name="MainRender" access="private">
		<broadcasts>
			<!-- get page credentials for EDIT mode to determine whether to display the Edit this Page link -->
			<message name="PageChildren" />
			<message name="GetPageRender" />
			<message name="NeedPageCredentials">
				<argument name="pageMode" value="EDIT" />
			</message>
			<message name="ValidatePageCredentials" /><!-- need to "validate" to store the pageAuth for EDIT in the view state -->
			<message name="LogPageView" />
		</broadcasts>
		<views>
			<include name="subpagelist" template="dsp.subpagelist.cfm" />
			<include name="body" template="dsp.body.cfm" />
		</views>
		<results>
			<result name="nonhtml" do="NonHtmlLayout" />
			<result do="Layout" />
		</results>
	</event-handler>

	<event-handler name="InvalidRole">
		<broadcasts />
		<views>
			<include name="body" template="dsp.invalidrole.cfm" />
		</views>
		<results>
			<result do="Layout" />
		</results>
	</event-handler>

	<event-handler name="UserInfo">
		<broadcasts>
			<message name="CheckIfLoggedIn">
				<argument name="returnToEvent" value="UserInfo" />
			</message>
		</broadcasts>
		<views>
			<include name="body" template="dsp.userinfo.cfm" />
		</views>
		<results>
			<result do="Layout" />
		</results>
	</event-handler>

	<event-handler name="Edit">
		<broadcasts>
			<message name="CheckIfLoggedIn">
				<argument name="returnToEvent" value="Main" />
				<argument name="pageMode" value="EDIT" />
			</message>
			<!-- check user vs. page security to see if we can even output this page  -->
			<message name="NeedPageCredentials">
				<argument name="pageMode" value="EDIT" />
			</message>
			<message name="NeedUserCredentials" />
			<message name="ValidatePageCredentials" />
		</broadcasts>
		<views />
		<results>
			<result name="invalidRole" do="InvalidRole" />
			<result name="validRole" do="EditRender" />
		</results>
	</event-handler>

	<event-handler name="EditRender" access="private">
		<broadcasts>
			<message name="EditInstructions" />
			<message name="NeedDefaultPageAuthRoles" />
		</broadcasts>
		<views>
			<include name="body" template="dsp.edit.cfm" />
		</views>
		<results>
			<result do="Layout" />
		</results>
	</event-handler>

	<event-handler name="MovePageForm">
		<broadcasts>
			<message name="CheckIfLoggedIn">
				<argument name="returnToEvent" value="Main" />
				<argument name="pageMode" value="MOVE" />
			</message>
			<message name="NeedPageCredentials">
				<argument name="pageMode" value="MOVE" />
			</message>
			<message name="NeedUserCredentials" />
			<message name="ValidatePageCredentials" />
		</broadcasts>
		<views />
		<results>
			<result name="invalidRole" do="InvalidRole" />
			<result name="validRole" do="MovePageFormRender" />
		</results>
	</event-handler>

	<event-handler name="MovePageFormRender" access="private">
		<broadcasts />
		<views>
			<include name="body" template="dsp.movepageform.cfm" />
		</views>
		<results>
			<result do="Layout" />
		</results>
	</event-handler>

	<event-handler name="MovePage">
		<broadcasts>
			<message name="CheckIfLoggedIn">
				<argument name="returnToEvent" value="MovePage" />
				<argument name="pageMode" value="MOVE" />
			</message>
			<message name="NeedPageCredentials">
				<argument name="pageMode" value="MOVE" />
			</message>
			<message name="NeedUserCredentials" />
			<message name="ValidatePageCredentials" />
		</broadcasts>
		<results>
			<result name="invalidRole" do="InvalidRole" />
			<result name="validRole" do="MovePageRender" />
		</results>
	</event-handler>
	
	<event-handler name="MovePageRender" access="private">
		<broadcasts>
			<message name="MovePage" />
		</broadcasts>
		<results>
			<result name="success" do="GenericMessage"/>
			<result name="invalid" do="MovePageForm" />
		</results>
	</event-handler>
	
	<event-handler name="DeletePageForm">
		<broadcasts>
			<message name="CheckIfLoggedIn">
				<argument name="returnToEvent" value="Main" />
				<argument name="pageMode" value="DELETE" />
			</message>
			<message name="NeedPageCredentials">
				<argument name="pageMode" value="DELETE" />
			</message>
			<message name="NeedUserCredentials" />
			<message name="ValidatePageCredentials" />
		</broadcasts>
		<views />
		<results>
			<result name="invalidRole" do="InvalidRole" />
			<result name="validRole" do="DeletePageFormRender" />
		</results>
	</event-handler>

	<event-handler name="DeletePageFormRender" access="private">
		<broadcasts />
		<views>
			<include name="body" template="dsp.deletepageform.cfm" />
		</views>
		<results>
			<result do="Layout" />
		</results>
	</event-handler>

	<event-handler name="DeletePage">
		<broadcasts>
			<message name="CheckIfLoggedIn">
				<argument name="returnToEvent" value="DeletePage" />
				<argument name="pageMode" value="DELETE" />
			</message>
			<message name="NeedPageCredentials">
				<argument name="pageMode" value="DELETE" />
			</message>
			<message name="NeedUserCredentials" />
			<message name="ValidatePageCredentials" />
		</broadcasts>
		<results>
			<result name="invalidRole" do="InvalidRole" />
			<result name="validRole" do="DeletePageRender" />
		</results>
	</event-handler>
